repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml # Checks toml files for parseable syntax
        exclude: ^uv\.lock$
      - id: check-json # Checks json files for parseable syntax
      - id: check-added-large-files # Prevents giant files from being committed
      - id: check-case-conflict # Checks for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Checks for files that contain merge conflict strings
      - id: check-yaml # Checks yaml files for parseable syntax
      - id: detect-private-key # Detects the presence of private keys
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline
      - id: fix-byte-order-marker # Removes utf-8 byte order marker
      - id: mixed-line-ending # Replaces or checks mixed line ending
      - id: trailing-whitespace # Trims trailing whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
